name: package
on: [pull_request, push]


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Publish to the Maven Central Repository
        run: mvn package